### ISSUE TITLE
/libicsneo/platform/posix/ftdi.cpp:8:10: fatal error: libusb.h: No such file or directory

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/libicsneo#46]
The project fails to build since https://github.com/intrepidcs/libicsneo/commit/82954d9190938c33f91e2b03c81c2f964cc427ce with the following error:

```
[ 66%] Building CXX object CMakeFiles/icsneocpp.dir/platform/posix/ftdi.cpp.o
/libicsneo/platform/posix/ftdi.cpp:8:10: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/icsneocpp.dir/build.make:397: recipe for target 'CMakeFiles/icsneocpp.dir/platform/posix/ftdi.cpp.o' failed
make[2]: *** [CMakeFiles/icsneocpp.dir/platform/posix/ftdi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/icsneocpp.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:282: recipe for target 'CMakeFiles/icsneocpp.dir/all' failed
Makefile:110: recipe for target 'all' failed
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release .. && make -j 9' returned a non-zero code: 2
```

**Comment by hollinsky-intrepid** [comment]
Ahh yes I've seen this and I've been meaning to track down exactly why. It resolves itself with another `cmake ..`, as a temporary workaround.

**Comment by hollinsky-intrepid** [comment]
Oh, you know what, looking at commit you posted I think I see it, thank you!

**Comment by pierreluctg** [comment]
Thank you @hollinsky-intrepid
